
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri May 16 18:14:02 BRT 2014
//----------------------------------------------------

package oficial;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_IGUAL = 15;
  public static final int READ = 8;
  public static final int ELSE = 4;
  public static final int RPAREN = 19;
  public static final int THEN = 3;
  public static final int SEMI = 20;
  public static final int END = 5;
  public static final int OP_ATRIB = 17;
  public static final int IF = 2;
  public static final int LPAREN = 18;
  public static final int WRITE = 9;
  public static final int ID = 10;
  public static final int OP_SUB = 12;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int OP_MQ = 16;
  public static final int OP_ADD = 11;
  public static final int error = 1;
  public static final int OP_QUOC = 14;
  public static final int UNTIL = 7;
  public static final int OP_MULT = 13;
  public static final int REPEAT = 6;
}

