
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 19 22:04:04 BRT 2014
//----------------------------------------------------

package compartilhado;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_IGUAL = 14;
  public static final int READ = 8;
  public static final int ELSE = 4;
  public static final int RPAREN = 18;
  public static final int THEN = 3;
  public static final int SEMI = 19;
  public static final int END = 5;
  public static final int OP_ATRIB = 16;
  public static final int IF = 2;
  public static final int LPAREN = 17;
  public static final int ID = 21;
  public static final int WRITE = 9;
  public static final int OP_SUB = 11;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int OP_MQ = 15;
  public static final int OP_ADD = 10;
  public static final int error = 1;
  public static final int OP_QUOC = 13;
  public static final int UNTIL = 7;
  public static final int OP_MULT = 12;
  public static final int REPEAT = 6;
}

