
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 08 06:10:10 BRT 2014
//----------------------------------------------------

package Example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPAREN = 6;
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int NUMBER = 7;
  public static final int SEMI = 2;
  public static final int LPAREN = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
}

